# Generated by Django 5.1.5 on 2025-07-01 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KapitalBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=25)),
                ('card_type', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_month', models.IntegerField(default=0)),
                ('expiry_year', models.IntegerField(default=0)),
                ('cvv', models.IntegerField(default=1)),
                ('currency', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('iban', models.CharField(max_length=34)),
                ('account_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('pending', 'Pending'), ('closed', 'Closed')], max_length=16)),
                ('loan_amount', models.DecimalField(decimal_places=1, max_digits=20)),
                ('loan_term', models.IntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_payment', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=30)),
                ('transaction_amount', models.DecimalField(decimal_places=3, max_digits=30)),
                ('timestamp', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('fin_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapitalbank_receivers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapitalbank_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
